package:
  format-version: "1.0.0"
  name: "wireless_thread"
  type: "package"
  status: "production"
  required: false
  version: "v1.3.0"

  dependencies:
    - name: "wireless_15_4_phy"
      type: "package"
      version: "v1.4.0" 
    - name: "openthread"
      type: "package"
      version: "mchp_harmony_wireless_thread_v1.3.0"

