package:
  format-version: "1.0.0"
  name: "wireless_thread"
  type: "package"
  status: "production"
  required: false
  version: "v1.3.0"

  dependencies:
    - name: "wireless_15_4_phy"
      type: "package"
      version: "v1.4.0-rc.1" 
    - name: "openthread"
      type: "package"
      version: "OT_v1.4.0_RC1"

