package:
  format-version: "1.0.0"
  name: "wireless_thread"
  type: "api"
  status: "beta"
  required: false
  version: "1.0.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.14.0"
    - name: "dev_packs"
      type: "package"
      version: "3.17.0"
    - name: "bsp"
      type: "package"
      version: "3.16.0"
    - name: "core"
      type: "package"
      version: "3.13.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "10.5.1"
    - name: "crypto"
      type: "package"
      version: "3.8.0"
    - name: "wolfssl"
      type: "package"
      version: "5.4.0"
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "1.1.0"
    - name: "wireless_15_4_phy"
      type: "package"
      version: "1.1.0" 
    - name: "openthread"
      type: "package"
      version: "mchp_harmony_wireless_thread_v1.0.0"

