package:
  format-version: "1.0.0"
  name: "wireless_thread"
  type: "package"
  status: "production"
  required: false
  version: "v1.1.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.18.3"
    - name: "bsp"
      type: "package"
      version: "v3.18.0"
    - name: "core"
      type: "package"
      version: "v3.13.3"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"
    - name: "crypto"
      type: "package"
      version: "v3.8.1"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "v1.3.1"
    - name: "wireless_15_4_phy"
      type: "package"
      version: "v1.2.0" 
    - name: "openthread"
      type: "package"
      version: "thread-reference-20230706"

