package:
  format-version: "1.0.0"
  name: "wireless_thread"
  type: "package"
  status: "production"
  required: false
  version: "v1.2.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.19.0"
    - name: "bsp"
      type: "package"
      version: "v3.20.0"
    - name: "core"
      type: "package"
      version: "v3.13.4"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v11.1.0"
    - name: "crypto"
      type: "package"
      version: "v3.8.1"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "v1.4.0"
    - name: "wireless_15_4_phy"
      type: "package"
      version: "v1.3.0" 
    - name: "openthread"
      type: "package"
      version: "thread-reference-20230706"

